ASUS TUF GAMING A15@ASUSTUF-ALVINZP MINGW64 ~/Desktop
$ ./ubah-semua-private.sh
📦 Mengambil semua repo milik alvinzanuaputra...
🔄 Mengubah semua repo PRIVATE menjadi PUBLIC...
➡️  Mengubah person-website menjadi public...
✓ Edited repository alvinzanuaputra/person-website
➡️  Mengubah alvinzanuaputra menjadi public...
✓ Edited repository alvinzanuaputra/alvinzanuaputra
➡️  Mengubah anime-versi2 menjadi public...
✓ Edited repository alvinzanuaputra/anime-versi2
➡️  Mengubah usahaku-topup_alvin menjadi public...
HTTP 422: Validation Failed (https://api.github.com/repos/alvinzanuaputra/usahaku-topup_alvin)
Private forks can't be made public
➡️  Mengubah anime-versi1 menjadi public...
✓ Edited repository alvinzanuaputra/anime-versi1
➡️  Mengubah soundofpraise-php menjadi public...
✓ Edited repository alvinzanuaputra/soundofpraise-php
➡️  Mengubah movie-stream-phpmurni menjadi public...
✓ Edited repository alvinzanuaputra/movie-stream-phpmurni
➡️  Mengubah motion-movies-laravel10 menjadi public...
✓ Edited repository alvinzanuaputra/motion-movies-laravel10
➡️  Mengubah finalpro-pbo-Csharp menjadi public...
✓ Edited repository alvinzanuaputra/finalpro-pbo-Csharp
➡️  Mengubah jarkom-5-j24-a05 menjadi public...
✓ Edited repository alvinzanuaputra/jarkom-5-j24-a05
➡️  Mengubah Jarkom-4-j24-a05 menjadi public...
✓ Edited repository alvinzanuaputra/Jarkom-4-j24-a05
➡️  Mengubah Kuroni-Impossible-Calculation menjadi public...
✓ Edited repository alvinzanuaputra/Kuroni-Impossible-Calculation
➡️  Mengubah handgesture-iot menjadi public...
✓ Edited repository alvinzanuaputra/handgesture-iot
➡️  Mengubah WeapMathh_2D-Game menjadi public...
✓ Edited repository alvinzanuaputra/WeapMathh_2D-Game
➡️  Mengubah fp-pbo-cat-games menjadi public...
✓ Edited repository alvinzanuaputra/fp-pbo-cat-games
➡️  Mengubah jarkom-3-j24-a05-1 menjadi public...
HTTP 422: Validation Failed (https://api.github.com/repos/alvinzanuaputra/jarkom-3-j24-a05-1)
Private forks can't be made public
➡️  Mengubah alvinphp menjadi public...
✓ Edited repository alvinzanuaputra/alvinphp
➡️  Mengubah task3-ets-artikel menjadi public...
✓ Edited repository alvinzanuaputra/task3-ets-artikel
➡️  Mengubah Jarkom-1-j24-a05 menjadi public...
✓ Edited repository alvinzanuaputra/Jarkom-1-j24-a05
➡️  Mengubah Jarkom-2-j24-a05 menjadi public...
✓ Edited repository alvinzanuaputra/Jarkom-2-j24-a05
➡️  Mengubah balapankuda-java menjadi public...
✓ Edited repository alvinzanuaputra/balapankuda-java
➡️  Mengubah task-1-websiteLecture menjadi public...
✓ Edited repository alvinzanuaputra/task-1-websiteLecture
➡️  Mengubah installDVWA menjadi public...
✓ Edited repository alvinzanuaputra/installDVWA
➡️  Mengubah kernel-bochs menjadi public...
✓ Edited repository alvinzanuaputra/kernel-bochs
➡️  Mengubah mathcul-its menjadi public...
✓ Edited repository alvinzanuaputra/mathcul-its
➡️  Mengubah weapmath menjadi public...
✓ Edited repository alvinzanuaputra/weapmath
➡️  Mengubah alvinzanuaputra_ menjadi public...
✓ Edited repository alvinzanuaputra/alvinzanuaputra_
➡️  Mengubah docker-laravel menjadi public...
✓ Edited repository alvinzanuaputra/docker-laravel
➡️  Mengubah iot-js_nodemon menjadi public...
✓ Edited repository alvinzanuaputra/iot-js_nodemon
➡️  Mengubah alvinzanua menjadi public...
✓ Edited repository alvinzanuaputra/alvinzanua
➡️  Mengubah alvinznutra-docker menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-docker
➡️  Mengubah alvinznutra_Sistem-Operasi menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra_Sistem-Operasi
➡️  Mengubah alvinznutra-fuse1 menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-fuse1
➡️  Mengubah spotify-alvin menjadi public...
✓ Edited repository alvinzanuaputra/spotify-alvin
➡️  Mengubah alvinznutra-shop menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-shop
➡️  Mengubah alvinznutra-tesla.github.io menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-tesla.github.io
➡️  Mengubah Modul-scripting menjadi public...
✓ Edited repository alvinzanuaputra/Modul-scripting
➡️  Mengubah alvinznutra-netflixclone menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-netflixclone
➡️  Mengubah alvinzanuaputra__ menjadi public...
✓ Edited repository alvinzanuaputra/alvinzanuaputra__
➡️  Mengubah alvin-c-language menjadi public...
✓ Edited repository alvinzanuaputra/alvin-c-language
➡️  Mengubah alvin-cpp-languange menjadi public...
✓ Edited repository alvinzanuaputra/alvin-cpp-languange
➡️  Mengubah alvin-python-language menjadi public...
✓ Edited repository alvinzanuaputra/alvin-python-language
➡️  Mengubah alvin-shell menjadi public...
✓ Edited repository alvinzanuaputra/alvin-shell
➡️  Mengubah alvinznutra-NontonMovie menjadi public...
✓ Edited repository alvinzanuaputra/alvinznutra-NontonMovie
➡️  Mengubah alvin-spaceport menjadi public...
✓ Edited repository alvinzanuaputra/alvin-spaceport
➡️  Mengubah alvin-profilesite menjadi public...
✓ Edited repository alvinzanuaputra/alvin-profilesite
➡️  Mengubah foyuu menjadi public...
✓ Edited repository alvinzanuaputra/foyuu
🎉 Selesai! Semua repo PRIVATE sudah diubah jadi PUBLIC.